name: quart
version: 0.0.2
author: Yehor Lvivski <lvivski@gmail.com>
description: Minimalist Dart library with a jQuery-compatible API
homepage: http://github.com/lvivski/quart
dependencies:
  unittest: '>=0.2.7'
  browser: any
