name: quart
version: 0.0.1+hotfix2
author: Yehor Lvivski <lvivski@gmail.com>
description: Minimalist Dart library with a jQuery-compatible API
homepage: http://github.com/lvivski/quart
dependencies:
  browser: any
